name: oasis
description: "App empleabilidad"
publish_to: 'none'
version: 1.13.0+13

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Estilos ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animations: ^2.1.0
  lottie: ^3.3.2
  flutter_svg: ^2.2.1

  # --- Estado & Navegaci√≥n ---
  go_router: ^16.2.5
  flutter_riverpod: ^2.5.1

  # --- Data & Persistencia ---
  dio: ^5.9.0
  shared_preferences: ^2.3.3
  web_socket_channel: ^3.0.0

  top_snackbar_flutter: ^3.3.0
  email_validator: ^2.1.17
  smooth_page_indicator: ^1.2.1
  equatable: ^2.0.7
  intl: ^0.19.0
  sticky_headers: ^0.3.0

  cached_network_image: ^3.3.1
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_n_01.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_n_01.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/